"""add score_factors, drop server-side timestamp defaults

Revision ID: 52f5669fdf0c
Revises: ad2143b64ebf
Create Date: 2026-08-14 22:18:02.018107
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '52f5669fdf0c'
down_revision: Union[str, None] = 'ad2143b64ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiatives', sa.Column('score_factors', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('initiatives', 'score_factors')
    # ### end Alembic commands ###
